In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns


%matplotlib inline

In [2]:
df=pd.read_csv("../data/AQI_Data.csv")
df.head()

,From Date,PM2.5 (ug/m3),PM10 (ug/m3),NO2 (ug/m3),NH3 (ug/m3),SO2 (ug/m3),CO (mg/m3),Ozone (ug/m3),Station_Id,Year,...,Time,Hour,CO (ug/m3),PM25_SI,PM10_SI,NO2_SI,SO2_SI,CO_SI,O3_SI,AQI
0,01-07-2016 10:00,10.67,39.0,39.2,7.07,6.60,0.48,14.5,AP001,2016,...,10:00:00,10,480.0,17.783333,39.0,49.000000,8.250,24.0,14.5,49.000000
1,01-07-2016 11:00,2.00,39.0,41.9,7.40,NaN,0.49,15.0,AP001,2016,...,11:00:00,11,490.0,3.333333,39.0,52.130769,NaN,24.5,15.0,52.130769
2,01-07-2016 12:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AP001,2016,...,12:00:00,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01-07-2016 13:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AP001,2016,...,13:00:00,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01-07-2016 14:00,20.50,50.0,43.6,6.35,6.38,0.47,10.5,AP001,2016,...,14:00:00,14,470.0,34.166667,50.0,54.266667,7.975,23.5,10.5,54.266667

In [10]:
print(f"This is shape of the Data: {df.shape}")
df.info()
print("This describes the DataFrame: ")
print(f"{df.describe()}")
df.isnull().sum()

This is shape of the Data: (1048575, 22)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 22 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   From Date      1048575 non-null  object
 1   PM2.5 (ug/m3)  819117 non-null   float64
 2   PM10 (ug/m3)   675283 non-null   float64
 3   NO2 (ug/m3)    850419 non-null   float64
 4   NH3 (ug/m3)    655962 non-null   float64
 5   SO2 (ug/m3)    838042 non-null   float64
 6   CO (mg/m3)     834183 non-null   float64
 7   Ozone (ug/m3)  846515 non-null   float64
 8   Station_Id     1048575 non-null  object
 9   Year           1048575 non-null  int64
 10  Month          1048575 non-null  int64
 11  Day            1048575 non-null  int64
 12  Time           1048575 non-null  object
 13  Hour           1048575 non-null  int64
 14  CO (ug/m3)     834183 non-null   float64
 15  PM25_SI        804036 non-null   float64
 16  PM10_SI        668425 non-null   float64
 17  NO2_SI         842193 non-null   float64
 18  SO2_SI         836398 non-null   float64
 19  CO_SI          834183 non-null   float64
 20  O3_SI          839437 non-null   float64
 21  AQI            887881 non-null   float64
dtypes: float64(15), int64(4), object(3)
memory usage: 176.0+ MB
This describes the DataFrame:
       PM2.5 (ug/m3)   PM10 (ug/m3)    NO2 (ug/m3)    NH3 (ug/m3)  \
count  819117.000000  675283.000000  850419.000000  655962.000000
mean       74.287268     136.010466      29.072602      17.421697
std        79.001019     123.002766      31.286334      17.883788
min         0.010000       0.010000       0.010000       0.010000
25%        24.500000      51.080000       8.970000       6.820000
50%        49.150000      95.750000      18.550000      12.350000
75%        95.940000     183.070000      37.910000      21.340000
max      1000.000000    1000.000000     495.110000     493.100000

         SO2 (ug/m3)     CO (mg/m3)  Ozone (ug/m3)          Year  \
count  838042.000000  834183.000000  846515.000000  1.048575e+06
mean       11.008871       0.964562      33.051940  2.020488e+03
std        13.828333       0.964181      31.024365  2.143897e+00
min         0.010000       0.000000       0.010000  2.012000e+03
25%         3.770000       0.440000      11.230000  2.020000e+03
50%         7.070000       0.730000      22.550000  2.021000e+03
75%        13.220000       1.210000      45.600000  2.022000e+03
max       199.900000      46.360000     200.000000  2.023000e+03

              Month           Day          Hour     CO (ug/m3)        PM25_SI  \
count  1.048575e+06  1.048575e+06  1.048575e+06  834183.000000  804036.000000
mean   6.410681e+00  1.579647e+01  1.150244e+01     964.562284     135.862300
std    3.603725e+00  8.807376e+00  6.922462e+00     964.181426     122.806156
min    1.000000e+00  1.000000e+00  0.000000e+00       0.000000       0.016667
25%    3.000000e+00  8.000000e+00  6.000000e+00     440.000000      40.000000
50%    6.000000e+00  1.600000e+01  1.200000e+01     730.000000      81.413793
75%    1.000000e+01  2.300000e+01  1.800000e+01    1210.000000     220.356207
max    1.200000e+01  3.100000e+01  2.300000e+01   46360.000000     500.000000

             PM10_SI         NO2_SI         SO2_SI          CO_SI  \
count  668425.000000  842193.000000  836398.000000  834183.000000
mean      119.651705      35.432577      13.440067      44.649026
std        94.747912      36.599924      15.241317      31.569564
min         0.010000       0.012500       0.012500       0.000000
25%        51.530000      11.125000       4.712500      22.000000
50%        95.920000      22.875000       8.812500      36.500000
75%       155.961611      46.325000      16.462500      61.251251
max       500.000000     416.554074     140.368227     477.476092

               O3_SI            AQI
count  839437.000000  887881.000000
mean       33.442724     149.833670
std        33.485436     115.753919
min         0.010000       0.000000
25%        11.150000      61.741742
50%        22.280000     105.267241
75%        44.720000     215.508621
max       279.692308     500.000000

From Date             0
PM2.5 (ug/m3)    229458
PM10 (ug/m3)     373292
NO2 (ug/m3)      198156
NH3 (ug/m3)      392613
SO2 (ug/m3)      210533
CO (mg/m3)       214392
Ozone (ug/m3)    202060
Station_Id            0
Year                  0
Month                 0
Day                   0
Time                  0
Hour                  0
CO (ug/m3)       214392
PM25_SI          244539
PM10_SI          380150
NO2_SI           206382
SO2_SI           212177
CO_SI            214392
O3_SI            209138
AQI              160694
dtype: int64

In [11]:
missing_percent= df.isnull().mean()*100
print(missing_percent)

From Date         0.000000
PM2.5 (ug/m3)    21.882841
PM10 (ug/m3)     35.599933
NO2 (ug/m3)      18.897647
NH3 (ug/m3)      37.442529
SO2 (ug/m3)      20.078011
CO (mg/m3)       20.446034
Ozone (ug/m3)    19.269962
Station_Id        0.000000
Year              0.000000
Month             0.000000
Day               0.000000
Time              0.000000
Hour              0.000000
CO (ug/m3)       20.446034
PM25_SI          23.321079
PM10_SI          36.253964
NO2_SI           19.682140
SO2_SI           20.234795
CO_SI            20.446034
O3_SI            19.944973
AQI              15.324989
dtype: float64

In [13]:
si_cols = [col for col in df.columns if col.endswith('_SI')]
df = df.drop(columns=si_cols)
if 'AQI' in df.columns:
    df = df.drop(columns=['AQI'])

In [14]:
print("Remaining columns:")
print(df.columns)

Remaining columns:
Index(['From Date', 'PM2.5 (ug/m3)', 'PM10 (ug/m3)', 'NO2 (ug/m3)',
       'NH3 (ug/m3)', 'SO2 (ug/m3)', 'CO (mg/m3)', 'Ozone (ug/m3)',
       'Station_Id', 'Year', 'Month', 'Day', 'Time', 'Hour', 'CO (ug/m3)'],
      dtype='object')

In [15]:
df = df.sort_values(['Station_Id', 'Year', 'Month', 'Day', 'Hour'])
df = df.reset_index(drop=True)

In [19]:
df[['CO (mg/m3)', 'CO (ug/m3)']].head()

   CO (mg/m3)  CO (ug/m3)
0        0.48       480.0
1        0.49       490.0
2         NaN         NaN
3         NaN         NaN
4        0.47       470.0

In [18]:
df[['CO (mg/m3)', 'CO (ug/m3)']].corr()

            CO (mg/m3)  CO (ug/m3)
CO (mg/m3)         1.0         1.0
CO (ug/m3)         1.0         1.0

In [20]:
df = df.drop(columns=['CO (mg/m3)'])

In [26]:
pollutant_cols = [
    'PM2.5 (ug/m3)',
    'PM10 (ug/m3)',
    'NO2 (ug/m3)',
    'NH3 (ug/m3)',
    'SO2 (ug/m3)',
    'CO (ug/m3)',  
    'Ozone (ug/m3)'
]

df[pollutant_cols] = (
    df.groupby('Station_Id')[pollutant_cols]
      .transform(lambda x: x.interpolate(method='linear', limit_direction='both'))
)

print(df[pollutant_cols].isnull().sum())

PM2.5 (ug/m3)         0
PM10 (ug/m3)     222048
NO2 (ug/m3)           0
NH3 (ug/m3)      222048
SO2 (ug/m3)           0
CO (ug/m3)            0
Ozone (ug/m3)         0
dtype: int64

In [27]:
df.groupby('Station_Id')[['PM10 (ug/m3)', 'NH3 (ug/m3)']].apply(lambda x: x.isnull().all())

            PM10 (ug/m3)  NH3 (ug/m3)
Station_Id
AP001              False        False
AP002              False        False
AP003              False        False
AP004              False        False
AP005              False        False
AP006              False        False
AP007              False        False
AP008              False        False
AP009              False        False
AP010              False        False
AR001              False        False
AS001              False        False
AS002              False        False
AS003              False        False
AS004              False        False
AS005              False        False
AS006              False        False
AS007              False        False
AS008              False        False
AS009              False        False
BR001               True         True
BR002               True         True
BR003               True         True
BR004              False        False
BR005              False        False
BR006              False        False
BR007              False        False
BR008              False        False
BR009              False        False
BR010              False        False
BR011              False        False
BR012              False        False
BR013              False        False
BR014              False        False
BR015              False        False
BR016              False        False
BR017              False        False
BR018              False        False
BR019              False        False
BR020              False        False
BR021              False        False
BR022              False        False
BR023              False        False
BR024              False        False
BR025              False        False
BR026              False        False
BR027              False        False
BR028              False        False
BR029              False        False
BR030              False        False

In [28]:
df = df.drop(columns=['PM10 (ug/m3)', 'NH3 (ug/m3)'])

In [29]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 12 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   From Date      1048575 non-null  object
 1   PM2.5 (ug/m3)  1048575 non-null  float64
 2   NO2 (ug/m3)    1048575 non-null  float64
 3   SO2 (ug/m3)    1048575 non-null  float64
 4   Ozone (ug/m3)  1048575 non-null  float64
 5   Station_Id     1048575 non-null  object
 6   Year           1048575 non-null  int64
 7   Month          1048575 non-null  int64
 8   Day            1048575 non-null  int64
 9   Time           1048575 non-null  object
 10  Hour           1048575 non-null  int64
 11  CO (ug/m3)     1048575 non-null  float64
dtypes: float64(5), int64(4), object(3)
memory usage: 96.0+ MB
None
From Date        0
PM2.5 (ug/m3)    0
NO2 (ug/m3)      0
SO2 (ug/m3)      0
Ozone (ug/m3)    0
Station_Id       0
Year             0
Month            0
Day              0
Time             0
Hour             0
CO (ug/m3)       0
dtype: int64

In [30]:
df['Datetime'] = pd.to_datetime(
    df['From Date'],
    format='%d-%m-%Y %H:%M'
)

In [32]:
df = df.sort_values(['Station_Id', 'Datetime'])
df = df.reset_index(drop=True)
df = df.drop(columns=['Year', 'Month', 'Day', 'Hour'])

In [34]:
print(df['Datetime'].min(), df['Datetime'].max())
df['Datetime'].isnull().sum()

2012-07-01 00:00:00 2023-03-31 23:00:00

np.int64(0)